### ISSUE TITLE
Center an image using flexbox

### ISSUE THREAD

**Issue by binayaksadangi** [E-Cell-VSSUT/Hacktober2k22Tech#4]

**Comment by Shubhamsingh2747** [comment]
Hey @binayaksadangi , I would like work on this project. I am familiar with flexbox and would like to try this out. Please assign me this issue.

**Comment by PayalPadmalyaPrusty** [comment]
i want to contribute.Assign me

**Comment by Anugya12** [comment]
I want to contribute. Please assign me

**Comment by shitikanthananda** [comment]
I want to contribute.  Please assign me.

**Comment by niteshk700** [comment]
plz assign me

**Comment by Rajsekhar7** [comment]
I want to work on this.

**Comment by Abhishek8287** [comment]
@ravindranag Centring an image using flexbox..please check and merge it
